import { IArmadilloCommand, IArmadilloResponse, ITransactionSchema } from '../model/currency';
import { IEthereumNetwork } from '../model/network';
export declare function getSupportedNetworks(): string[];
export declare function getSupportedNetwork(network: string): IEthereumNetwork;
export declare function getFeeOptionUnit(): string;
export declare function isValidFeeOption(network: string, feeOpt: string): boolean;
export declare function isValidAddr(network: string, addr: string): boolean;
export declare function isValidNormAmount(amount: string): boolean;
export declare function convertNormAmountToBaseAmount(amount: string): string;
export declare function convertBaseAmountToNormAmount(amount: string): string;
export declare function getUrlForAddr(network: string, addr: string): string;
export declare function getUrlForTx(network: string, txid: string): string;
export declare function encodePubkeyToAddr(network: string, pubkey: string): string;
export declare function getFeeOptions(network: string): Promise<string[]>;
export declare function getHistorySchema(): ITransactionSchema[];
export declare function submitTransaction(network: string, signedTx: string): Promise<string>;
export declare function prepareCommandGetPubkey(network: string, accountIndex: number): IArmadilloCommand;
export declare function parsePubkeyResponse(walletRsp: IArmadilloResponse): string;
export declare function prepareCommandShowAddr(network: string, accountIndex: number): IArmadilloCommand;
